json.id result['timdex_record_id']
json.identifiers result['identifiers'] if result['identifiers']
json.source result['source']
json.title result['title']
json.contributors result['contributors'] if result['contributors']
json.publication_information result['publication_information'] if result['publication_information']
json.dates result['dates'] if result['dates']
json.notes result['notes'] if result['notes']
json.content_type result['content_type'] if result['content_type']
