AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "bin/**"

Metrics/BlockLength:
  CountComments: false # count full line comments?
  Max: 25
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "test/**/*.rb"
    - "test/test_helper.rb"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
