title: TIMDEX API Documentation
description: MIT Libraries TIMDEX API Documentation

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc4
plugins:
  - "jekyll-remote-theme"
  - "jekyll-seo-tag"

color_scheme: dark

exclude:
  - architecture-decisions

nav_external_links:
  - title: Reference Docs
    url: ./reference
    hide_icon: false # set to true to hide the external link icon - defaults to false

mermaid:
  version: "9.3.0"
