spectaql:
  # logoFile: ./assets/images/tim-timdex.svg
  # faviconFile: ./test/fixtures/favicon.png
  displayAllServers: true

introspection:
  # removeTrailingPeriodFromDescriptions: false
  # schemaFile: ./examples/data/schema.gql
  # metadataFile: ./examples/data/metadata.json
  # dynamicExamplesProcessingModule: ./examples/customizations/examples
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: TIMDEX API Reference
  description: Welcome to the TIMDEX API!
  contact:
    name: API Support
    email: timdex@mit.edu
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-introItems:
    - title: TIMDEX Overview, Guides, and Tutorials
      description: These reference docs are only part of our documentation. Please also see our [Guides and Tutorials](../).

servers:
  - url: https://timdex.mit.edu/graphql
    description: Production
    production: true

