name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shared:
    uses: mitlibraries/.github/.github/workflows/ruby-shared-ci.yml@6886f9574e40fab796c127d7e14d8db356c99124 # main
